"""this file reads the selected sales CSV/XLSX file, checks the expected columns,
and creates the month field used by the charts.
"""

from pathlib import Path
import re
import pandas as pd
import streamlit as st


REQUIRED_COLUMNS = {
    "transaction_id",
    "item",
    "total_spent",
    "location",
    "transaction_date",
    "province"
}

DATA_FILE = Path(__file__).resolve().parent.parent / "data" / "processed" / "cleaned_transactions.csv"
REPORTS_DIR = Path(__file__).resolve().parent.parent / "reports"


def clean_column_name(column):
    """Make clean team exports easier to connect without forcing exact header casing."""
    return re.sub(r"[^a-z0-9]+", "_", str(column).strip().lower()).strip("_")


def read_data_file(file):
    if file.suffix.lower() == ".csv":
        return pd.read_csv(file)
    return pd.read_excel(file, engine="openpyxl")


@st.cache_data(show_spinner=False)
def load_data():
    """Load the configured CSV/Excel file and prepare chart-ready columns."""
    file = DATA_FILE
    if not file.exists():
        return None, file, f"Data file not found: {file.name}. Update DATA_FILE in data.py"

    df = read_data_file(file).copy()
    df.columns = [clean_column_name(c) for c in df.columns]

    missing = sorted(REQUIRED_COLUMNS - set(df.columns))
    if missing:
        return None, file, (
            f"Missing required columns: {', '.join(missing)}. "
            "Check the spreadsheet headers or update REQUIRED_COLUMNS in data.py."
        )

    df["total_spent"] = pd.to_numeric(df["total_spent"], errors="coerce")
    df["transaction_date"] = pd.to_datetime(df["transaction_date"], errors="coerce")

    for col in ["item", "province", "location"]:
        df[col] = df[col].fillna("Unknown").astype(str).str.strip().replace("", "Unknown")

    df["month"] = df["transaction_date"].dt.to_period("M").dt.to_timestamp()
    return df, file, None


@st.cache_data(show_spinner=False)
def load_forecast_reports():
    """Load user-facing forecast outputs generated by run_model.py."""
    monthly_file = REPORTS_DIR / "monthly_forecast.csv"
    six_month_file = REPORTS_DIR / "six_month_forecast.csv"
    daily_file = REPORTS_DIR / "daily_forecast.csv"

    missing = [file.name for file in [monthly_file, six_month_file, daily_file] if not file.exists()]
    if missing:
        return None, None, None, f"Forecast file missing: {', '.join(missing)}. Run run_model.py test first."

    monthly = pd.read_csv(monthly_file)
    monthly.columns = [clean_column_name(c) for c in monthly.columns]
    monthly["month"] = pd.to_datetime(monthly["month"], errors="coerce").dt.to_period("M").dt.to_timestamp()
    monthly["monthly_forecast"] = pd.to_numeric(monthly["monthly_forecast"], errors="coerce")

    six_month = pd.read_csv(six_month_file)
    six_month.columns = [clean_column_name(c) for c in six_month.columns]
    six_month["date"] = pd.to_datetime(six_month["date"], errors="coerce")
    six_month["forecast"] = pd.to_numeric(six_month["forecast"], errors="coerce")
    six_month["month"] = six_month["date"].dt.to_period("M").dt.to_timestamp()

    daily = pd.read_csv(daily_file)
    daily.columns = [clean_column_name(c) for c in daily.columns]
    daily["date"] = pd.to_datetime(daily["date"], errors="coerce")
    daily["forecast"] = pd.to_numeric(daily["forecast"], errors="coerce")
    daily["weekday"] = pd.Categorical(
        daily["date"].dt.day_name().str[:3],
        ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
        ordered=True,
    )

    return monthly, six_month, daily, None
